Repository bitname-protocol/bitname-cli, pull requests merged in 2018-02, with the labels that each got.

#45 Autodeploy docs from travis
  .travis.yml
  README.md
Labels: documentation, in progress

#51 Switch from blockcypher to electrum for network information
  __mocks__/electrum-client.ts
  __mocks__/history.json
  __mocks__/txs.json
  __mocks__/unspent.json
  __tests__/__snapshots__/net.test.ts.snap
  __tests__/chain.test.ts
  __tests__/net-bad-fees.ts
  __tests__/net-server-lists.test.ts
  __tests__/net.test.ts
  data/servers.json
  data/servers_testnet.json
  index.ts
  lib/__mocks__/__mockData__/blockcypher_full_txs.json
  lib/__mocks__/__mockData__/blockcypher_no_utxos.json
  lib/__mocks__/__mockData__/blockcypher_utxo_in_multiple_chains.json
  lib/__mocks__/__mockData__/blockcypher_utxos.json
  lib/__mocks__/__mockData__/fetchAllTX/mj1bija2CGxykXXyjohk5DtXvkQEPpdg1H.json
  lib/__mocks__/__mockData__/fetchAllTX/mk8cJh83q2JKBNguuzamfN1LZ9aECtnVJ7.json
  lib/__mocks__/__mockData__/fetchAllTX/muYWRM71cj5LH1aJ16FLFP2PHn2SHs3FpA.json
  lib/__mocks__/__mockData__/fetchAllTX/n4QGUi9Ds29DBcN8MdPcHwb3rt3uh8NLHw.json
  lib/__mocks__/netUtils.ts
  lib/chain.ts
  lib/net.ts
  lib/netUtils.ts
  lib/txs.ts
  package.json
  regtestTest.ts
  types/bcoin/lib/bcoin.d.ts
  types/electrum-client/index.d.ts
  types/index.d.ts
  update-electrum-peers.js
  yarn.lock
Labels: in progress

#52 added documentation to verify.ts
  lib/verify.ts
Labels: Ready for review

#53 Add commitment stage to guide in README
  .travis.yml
  README.md
  __tests__/net-bad-fees.test.ts
  index.ts
Labels: Ready for review, in progress
